version: "3.9"
services:
  backend:
    container_name: backend
    ports:
      - '88:88'
    build:
      context: ./
      dockerfile: ./infra/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 88 --reload
    restart: on-failure
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./:/usr/src/app
    network_mode: host